#!/bin/bash
#===============================================================================
# DFIR Monitor Deployment Script
# Forensic-Grade "Black Box" Recorder for Linux VPS
#
# SAFETY GUARANTEES:
#   - Runs at nice -n 19 (LOWEST CPU priority)
#   - ionice -c3 (Idle I/O class - only uses disk when system is idle)
#   - Memory limited to 256MB max
#   - Will NEVER block web traffic or touch web application files
#   - Automatic watchdog kills if CPU > 10% sustained
#===============================================================================

set -euo pipefail

# Configuration
readonly INSTALL_DIR="/opt/dfir"
readonly LOG_FILE="/var/log/dfir_monitor.json"
readonly PID_FILE="/var/run/dfir_monitor.pid"
readonly RETENTION_DAYS=14

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info()  { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

#===============================================================================
# VALIDATION
#===============================================================================

check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root (use sudo)"
        exit 1
    fi
}

detect_os() {
    if command -v apt-get &> /dev/null; then
        PKG_MANAGER="apt"
        OS_FAMILY="debian"
    elif command -v dnf &> /dev/null; then
        PKG_MANAGER="dnf"
        OS_FAMILY="rhel"
    elif command -v yum &> /dev/null; then
        PKG_MANAGER="yum"
        OS_FAMILY="rhel"
    else
        log_error "Unsupported OS. Requires apt (Debian/Ubuntu) or yum/dnf (RHEL/CentOS)"
        exit 1
    fi
    log_info "Detected package manager: $PKG_MANAGER ($OS_FAMILY family)"
}

detect_interface() {
    # Find the primary public-facing interface
    IFACE=$(ip route get 8.8.8.8 2>/dev/null | grep -oP 'dev \K\S+' | head -1)
    if [[ -z "$IFACE" ]]; then
        IFACE=$(ip link show | grep -E '^[0-9]+:' | grep -v 'lo:' | head -1 | cut -d: -f2 | tr -d ' ')
    fi
    log_info "Detected network interface: $IFACE"
}

#===============================================================================
# DEPENDENCY INSTALLATION
#===============================================================================

install_dependencies_debian() {
    log_info "Updating package lists..."
    apt-get update -qq

    log_info "Installing core dependencies..."
    apt-get install -y -qq python3 python3-pip auditd audispd-plugins curl gnupg

    # Install Zeek from official repository
    if ! command -v zeek &> /dev/null; then
        log_info "Adding Zeek repository..."
        echo 'deb http://download.opensuse.org/repositories/security:/zeek/xUbuntu_22.04/ /' | \
            tee /etc/apt/sources.list.d/security:zeek.list
        curl -fsSL 'https://download.opensuse.org/repositories/security:zeek/xUbuntu_22.04/Release.key' | \
            gpg --dearmor | tee /etc/apt/trusted.gpg.d/security_zeek.gpg > /dev/null
        apt-get update -qq
        apt-get install -y -qq zeek || {
            log_warn "Zeek repo install failed, trying zeek-lts..."
            apt-get install -y -qq zeek-lts || true
        }
    fi
}

install_dependencies_rhel() {
    log_info "Installing core dependencies..."
    $PKG_MANAGER install -y -q python3 python3-pip audit audit-libs curl

    # Install Zeek from official repository
    if ! command -v zeek &> /dev/null; then
        log_info "Adding Zeek repository..."
        cat > /etc/yum.repos.d/zeek.repo << 'EOF'
[zeek]
name=Zeek Repository
baseurl=https://download.opensuse.org/repositories/security:/zeek/CentOS_8/
enabled=1
gpgcheck=1
gpgkey=https://download.opensuse.org/repositories/security:/zeek/CentOS_8/repodata/repomd.xml.key
EOF
        $PKG_MANAGER install -y zeek || {
            log_warn "Zeek installation from repo failed. Will continue without Zeek."
        }
    fi
}

install_dependencies() {
    case $OS_FAMILY in
        debian) install_dependencies_debian ;;
        rhel)   install_dependencies_rhel ;;
    esac
}

#===============================================================================
# AUDITD CONFIGURATION
#===============================================================================

configure_auditd() {
    log_info "Configuring Auditd rules..."

    # Create rules directory if it doesn't exist
    mkdir -p /etc/audit/rules.d

    # Write forensic audit rules
    cat > /etc/audit/rules.d/dfir.rules << 'EOF'
## DFIR Monitor - Forensic-Grade Audit Rules
## Generated by deploy_monitor.sh

# Delete all existing rules (clean slate)
-D

# Set buffer size (increase for high-traffic servers)
-b 8192

# Failure mode: 1 = printk, 2 = panic (use 1 for production)
-f 1

#===============================================================================
# PROCESS EXECUTION - Capture EVERY command executed
#===============================================================================
-a always,exit -F arch=b64 -S execve -k process_exec
-a always,exit -F arch=b32 -S execve -k process_exec

#===============================================================================
# NETWORK - Detect reverse shells and outbound connections
#===============================================================================
-a always,exit -F arch=b64 -S connect -k network_connect
-a always,exit -F arch=b64 -S accept -k network_accept
-a always,exit -F arch=b64 -S accept4 -k network_accept

#===============================================================================
# FILE INTEGRITY - Critical system files
#===============================================================================
-w /etc/passwd -p wa -k identity_file
-w /etc/shadow -p wa -k identity_file
-w /etc/group -p wa -k identity_file
-w /etc/sudoers -p wa -k sudoers_file
-w /etc/ssh/sshd_config -p wa -k sshd_config
-w /root/.ssh/ -p wa -k ssh_keys

#===============================================================================
# PRIVILEGE ESCALATION
#===============================================================================
-w /bin/su -p x -k priv_esc
-w /usr/bin/sudo -p x -k priv_esc
-w /usr/bin/passwd -p x -k passwd_change

# Make rules immutable (requires reboot to change)
# Uncomment for maximum security: -e 2
EOF

    # Restart auditd to apply rules
    log_info "Restarting auditd..."
    if command -v systemctl &> /dev/null; then
        systemctl restart auditd || service auditd restart
        systemctl enable auditd 2>/dev/null || true
    else
        service auditd restart
    fi

    # Verify rules loaded
    local rule_count
    rule_count=$(auditctl -l 2>/dev/null | wc -l)
    log_info "Loaded $rule_count audit rules"
}

#===============================================================================
# ZEEK CONFIGURATION
#===============================================================================

configure_zeek() {
    # Find Zeek installation
    local zeek_base=""
    for path in /opt/zeek /usr/local/zeek /usr/share/zeek; do
        if [[ -d "$path" ]]; then
            zeek_base="$path"
            break
        fi
    done

    if [[ -z "$zeek_base" ]]; then
        log_warn "Zeek not found. Network monitoring will be limited."
        return 0
    fi

    log_info "Configuring Zeek at $zeek_base..."

    # Configure local.zeek for JSON output
    mkdir -p "$zeek_base/share/zeek/site"
    cat > "$zeek_base/share/zeek/site/local.zeek" << 'EOF'
##! DFIR Monitor - Zeek Configuration
##! Optimized for forensic evidence collection

# Load standard scripts
@load base/frameworks/files
@load base/protocols/conn
@load base/protocols/dns
@load base/protocols/http
@load base/protocols/ssl
@load frameworks/files/hash-all-files
@load policy/protocols/conn/known-hosts
@load policy/protocols/conn/known-services
@load policy/protocols/ssl/validate-certs

# Enable JSON logging (CRITICAL for parsing)
redef LogAscii::use_json = T;

# Increase connection tracking for high-traffic servers
redef ConnSplitter::max_connections = 1000000;

# Log more SSL/TLS details
redef SSL::log_x509_cert_data = T;

# Capture JA3 fingerprints (if available)
@load policy/protocols/ssl/ja3
EOF

    # Configure node.cfg for interface
    if [[ -f "$zeek_base/etc/node.cfg" ]]; then
        cat > "$zeek_base/etc/node.cfg" << EOF
[zeek]
type=standalone
host=localhost
interface=$IFACE
EOF
    fi

    # Set log directory
    mkdir -p /var/log/zeek
    if [[ -f "$zeek_base/etc/zeekctl.cfg" ]]; then
        sed -i "s|LogDir.*|LogDir = /var/log/zeek|g" "$zeek_base/etc/zeekctl.cfg" 2>/dev/null || true
    fi

    # Deploy Zeek (if zeekctl exists)
    if command -v zeekctl &> /dev/null; then
        log_info "Deploying Zeek..."
        zeekctl deploy 2>/dev/null || zeekctl install && zeekctl start || {
            log_warn "zeekctl deploy failed. Try running 'zeekctl deploy' manually."
        }
    elif [[ -x "$zeek_base/bin/zeekctl" ]]; then
        "$zeek_base/bin/zeekctl" deploy 2>/dev/null || true
    fi
}

#===============================================================================
# LOGROTATE CONFIGURATION
#===============================================================================

configure_logrotate() {
    log_info "Configuring log rotation..."

    cat > /etc/logrotate.d/dfir_monitor << EOF
# DFIR Monitor - Daily Log Rotation
# Keeps $RETENTION_DAYS days of forensic logs

$LOG_FILE {
    daily
    rotate $RETENTION_DAYS
    compress
    delaycompress
    missingok
    notifempty
    dateext
    dateformat -%Y-%m-%d
    create 0640 root root
    postrotate
        # Signal monitor to reopen log file
        if [ -f $PID_FILE ]; then
            kill -HUP \$(cat $PID_FILE) 2>/dev/null || true
        fi
    endscript
}

# Also rotate Zeek logs
/var/log/zeek/current/*.log {
    daily
    rotate $RETENTION_DAYS
    compress
    delaycompress
    missingok
    notifempty
    dateext
    dateformat -%Y-%m-%d
    sharedscripts
    postrotate
        /usr/bin/zeekctl rotate 2>/dev/null || true
    endscript
}
EOF
}

#===============================================================================
# INSTALL MONITOR CORE
#===============================================================================

install_monitor_core() {
    log_info "Installing monitor_core.py..."

    # Create installation directory
    mkdir -p "$INSTALL_DIR"

    # Copy monitor script (expected to be in same directory as deploy script)
    local script_dir
    script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

    if [[ -f "$script_dir/monitor_core.py" ]]; then
        cp "$script_dir/monitor_core.py" "$INSTALL_DIR/monitor_core.py"
        chmod +x "$INSTALL_DIR/monitor_core.py"
    else
        log_error "monitor_core.py not found in $script_dir"
        log_error "Please ensure monitor_core.py is in the same directory as this script"
        exit 1
    fi

    # Create empty log file with correct permissions
    touch "$LOG_FILE"
    chmod 0640 "$LOG_FILE"
}

#===============================================================================
# START DAEMON (SAFETY-FIRST)
#===============================================================================

start_daemon() {
    log_info "Starting DFIR monitor daemon..."

    # Kill existing instances
    if [[ -f "$PID_FILE" ]]; then
        local old_pid
        old_pid=$(cat "$PID_FILE" 2>/dev/null)
        if [[ -n "$old_pid" ]] && kill -0 "$old_pid" 2>/dev/null; then
            log_info "Stopping existing monitor (PID: $old_pid)..."
            kill "$old_pid" 2>/dev/null || true
            sleep 2
        fi
    fi

    # Kill any orphaned processes
    pkill -f "monitor_core.py" 2>/dev/null || true
    sleep 1

    #===========================================================================
    # SAFETY MEASURES FOR YOUR 50,000+ USERS
    #===========================================================================
    # nice -n 19     : Lowest CPU scheduling priority
    # ionice -c3     : Idle I/O class (only uses disk when nothing else needs it)
    # Memory limit   : Set via ulimit to prevent runaway memory usage
    #===========================================================================

    # Start with maximum safety constraints
    nohup nice -n 19 ionice -c3 \
        /bin/bash -c '
            # Limit memory to 256MB (soft) and 512MB (hard)
            ulimit -v 524288  # 512MB virtual memory limit
            ulimit -m 262144  # 256MB resident set size limit

            exec python3 '"$INSTALL_DIR"'/monitor_core.py
        ' > /var/log/dfir_monitor_daemon.log 2>&1 &

    local new_pid=$!
    echo "$new_pid" > "$PID_FILE"

    # Wait and verify it started
    sleep 2
    if kill -0 "$new_pid" 2>/dev/null; then
        log_info "Monitor started successfully (PID: $new_pid)"
    else
        log_error "Monitor failed to start. Check /var/log/dfir_monitor_daemon.log"
        exit 1
    fi
}

#===============================================================================
# SYSTEMD SERVICE (OPTIONAL - MORE ROBUST)
#===============================================================================

create_systemd_service() {
    if ! command -v systemctl &> /dev/null; then
        return 0
    fi

    log_info "Creating systemd service..."

    cat > /etc/systemd/system/dfir-monitor.service << EOF
[Unit]
Description=DFIR Forensic Monitor - Black Box Recorder
Documentation=https://github.com/your-repo/dfir-monitor
After=network.target auditd.service
Wants=auditd.service

[Service]
Type=simple
ExecStart=/usr/bin/python3 $INSTALL_DIR/monitor_core.py
PIDFile=$PID_FILE
Restart=always
RestartSec=10

# SAFETY CONSTRAINTS - Protect your web application
Nice=19
IOSchedulingClass=idle
MemoryMax=256M
MemoryHigh=128M
CPUQuota=10%
CPUWeight=10

# Security hardening
NoNewPrivileges=false
ProtectSystem=strict
ProtectHome=read-only
ReadWritePaths=/var/log $INSTALL_DIR
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload

    log_info "Systemd service created. To use it instead of nohup:"
    log_info "  sudo systemctl enable dfir-monitor"
    log_info "  sudo systemctl start dfir-monitor"
}

#===============================================================================
# VERIFICATION
#===============================================================================

verify_installation() {
    log_info "Verifying installation..."

    local errors=0

    # Check auditd
    if systemctl is-active --quiet auditd 2>/dev/null || service auditd status &>/dev/null; then
        log_info "✓ Auditd is running"
    else
        log_warn "✗ Auditd is not running"
        ((errors++))
    fi

    # Check Zeek
    if command -v zeek &> /dev/null; then
        if pgrep -x zeek &> /dev/null || zeekctl status 2>/dev/null | grep -q running; then
            log_info "✓ Zeek is running"
        else
            log_warn "✗ Zeek is not running (run 'zeekctl start')"
        fi
    else
        log_warn "⚠ Zeek not installed (network monitoring limited)"
    fi

    # Check monitor
    if [[ -f "$PID_FILE" ]] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
        log_info "✓ Monitor daemon is running (PID: $(cat "$PID_FILE"))"
    else
        log_error "✗ Monitor daemon is not running"
        ((errors++))
    fi

    # Check log file
    if [[ -f "$LOG_FILE" ]]; then
        log_info "✓ Log file exists: $LOG_FILE"
    else
        log_warn "✗ Log file not yet created"
    fi

    return $errors
}

#===============================================================================
# MAIN
#===============================================================================

main() {
    echo "========================================"
    echo " DFIR Monitor - Forensic Black Box"
    echo " Deployment Script v1.0"
    echo "========================================"
    echo ""

    check_root
    detect_os
    detect_interface

    echo ""
    log_info "Installing dependencies..."
    install_dependencies

    echo ""
    log_info "Configuring security monitoring..."
    configure_auditd
    configure_zeek

    echo ""
    log_info "Setting up log management..."
    configure_logrotate

    echo ""
    install_monitor_core
    start_daemon

    echo ""
    create_systemd_service

    echo ""
    echo "========================================"
    verify_installation
    echo "========================================"

    echo ""
    log_info "Deployment complete!"
    echo ""
    echo "  Monitor PID: $(cat "$PID_FILE" 2>/dev/null || echo 'N/A')"
    echo "  Log File:    $LOG_FILE"
    echo "  Retention:   $RETENTION_DAYS days"
    echo ""
    echo "  View live logs: tail -f $LOG_FILE | jq ."
    echo "  Search logs:    zgrep 'pattern' /var/log/dfir_monitor.json*.gz"
    echo ""
    log_info "HINT: To find the 'Black Sheep' (insider threats),"
    log_info "Make sure your web app in ~/crud/ server logs the username!"
    echo ""
}

main "$@"
